### ISSUE TITLE
[Import] Products extraction

### ISSUE THREAD

**Issue by davidnuescheler** [davidnuescheler/theblog#64]
it looks like the products mentioned in a post are extracted somehow from the `href`, but it seems that the `svg src` could be a more reliable source for the svg icon at least? 

compare:
https://theblog.adobe.com/52-weeks-of-productivity/
https://theblog.helix-demo.xyz/ms/archive/posts/2020/52-weeks-of-productivity.html

**Comment by davidnuescheler** [comment]
i think as a more general statement, it would be desirable to make sure that there are no broken images throughout the posts....

**Comment by kptdobe** [comment]
Yes, that's a duplicate from #28.
The svg src is not necessarily reliable neither. For this example, we have: `Adobe_Scan_logo_512px.png`, `adobe-sign-logo.png`, `document-cloud.svg`
I think they also have multiple variations of the product names.

Links are also broken at the moment.

The way to go is introduce a product page that includes the link and image, so that the mapping can be done. 
But this does not change the fact that the author has to know the correct name of the product. In that specific case, I fixed the md to refer to correct product names (or at least names that refer to an icon).

I am working on it but I was just reluctant to redo the import process just 2 days before the demo.
