### ISSUE TITLE
[Import] sections

### ISSUE THREAD

**Issue by davidnuescheler** [davidnuescheler/theblog#66]
the current css assumes that there is only one section for the post body... it seems that the vast majority of the posts fulfill that assumption, however most recently one was imported that doesn't conform to that...

https://theblog.helix-demo.xyz/ms/archive/posts/2020/the-it-experts-guide-to-ai-and-content-management.html

it would be great, if in the short-term we could just ignore `hr` and not translate them to thematic breaks...

**Comment by kptdobe** [comment]
Nice edge case, I have never seen a post before with an `hr` in it. I'll patch the importer to ignore them.

**Comment by kptdobe** [comment]
What I have done:
- I patched the importer to exclude all the `hr`
- I re-imported the 2020 pages (we have enough to be the only one appearing on the homepage)
- I added the blog posts from yesterday
- I re-indexed the whole 2020 folder

I will check if new posts appear today (in my afternoon) and I will add them so that for the demo we'll have the same content than real site.
