### ISSUE TITLE
Multi-language support: translation and localization

### ISSUE THREAD

**Issue by rofe** [davidnuescheler/theblog#79]
Show end to end translation workflow incl. 3rd party translation service, e.g. English article into German and French. Show end to end workflow for local content.

**Comment by rofe** [comment]
We need a screen recording showing how an admin:
1. signs into OneDrive and navigates to the posts/en folder
1. selects an English document to translate into German and copies it to the translations/de folder
1. an automatic translation process gets kicked off (status?)
1. opens the translated document, checks translation and makes a few corrections
1. clicks a link to view a draft the translated blog post rendered by Helix (e.g. theblog-davidnuescheler.hlx.page/ms/translations/de/my-german-post.html)
1. moves the final document from translate/de to the posts/de folder
1. opens https://theblog.helix-demo.xyz/
1. switches language to German
1. sees new blog post at the top

**Comment by rofe** [comment]
@davidnuescheler anything to add or change?

**Comment by rofe** [comment]
adjusted the flow based on a review with @davidnuescheler

**Comment by kptdobe** [comment]
Here is the current status:

- GLaas deals nicely with docx and md, no need to add any logic / magic conversion
- We should NOT translate the file names, otherwise we lose capability to switch between languages...
- Flow is more simple: 
  - just dump a docx / md into `de/to-be-translated`, a task is automatically created in GLaas (see API https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=g11n&title=Integrating+with+Translation+Tasks+Workflow). *For the demo*: task has been manually created and can be shown.
  - standard translation process occurs, GLaas is just the proxy to SDL WorldServer where translators do their job. No need for extract emails or whatever, the existing tools do this job. Again, docx / md does not matter, both are digested into XLIFF and software propose various UIs to do the translation.
  - when done, translated docx / md comes back to GLaas and task is resolved.
  - file is then dowloaded automatically into the `de/review` folder (see poll or event API). *For the demo*: the file has already been prepared and stands in the `de/review` folder.
  - email "Ready for review" is sent by GLaas (checking with GLaas team if this is doable).
  - preview the file `https://theblog--davidnuescheler.hlx.page/ms/de/review/translated.html`
  - when ready, move the file to `de/post`
  - indexer sees the new file and adds it to the list (currently broken)

**Comment by kptdobe** [comment]
Tip: we can use the "Machine Learning" workflow to have translated documents with low effort. Pb: it also translates the "authored by", "posted on", all topics and all products. Just need to revert those changes. The rest is pretty decently translated (at least for a demo).

**Comment by MarquiseRosier** [comment]
@kptdobe that’s exciting!! may I suggest benchmarking against some standard dataset. Precision & Recall on translation services; I can do this if you give me name of what you used for French.

**Comment by rofe** [comment]
Recording done.
