### ISSUE TITLE
Bulk Editor: Export and Import table

### ISSUE THREAD

**Issue by davidnuescheler** [davidnuescheler/theblog#86]
For the sake of bulk editing topics and products, it would be great to be able to initially export let's say a CSV, that would look like this:

```
Path, Topics, Products
/ms/archive/posts/2020/adobe-character-animator-receives-emmy-award-for-technology-and-engineering.html, "Creativity, News, Audio & Video", "Character Animator"
/ms/archive/posts/2020/adobe-boosts-global-trust-with-apec-prp-certification.html, "News",
```

once exported it can and should be edited via excel or google sheets, and then the CSV should be able to be uploaded again and all the changes should easily be previewed (how many changes are going to be made, in which docs)

i think the table export could and should probably be something that is built using the index.

considering that this is one of the first times that we make changes to `.docx`, `.md` or `.gdoc` respectively i am not exactly sure where this would go. especially considering that to support this particular usecase there would be a highly customized action (or similar extension point) that would do the import of products and topics on a per document basis.

**Comment by tripodsan** [comment]
After discussing this f2f with @davidnuescheler  we came to the conclusion that using the index to generate the csv is wrong. since the editing is done on the original document, the table export should also be done on the original documents.

To start with, we also agreed to **only** support the bulk editor on the markdown files, stored in onedrive. the overall workflow might look like this:

**export**
1. traverse files and folders below root node(s) and filter out the editables (writeable markdown files)
2. for each editable, use some method to extract the required fields
3. generate a CSV table that contains document paths and the respective fields

**edit**
1. user opens generated CSV in excel or similar.
2. user updates the fields
3. user saves the table again as CSV

**import**
1. use _imports_ the CSV back
2. importer will go through all modified documents and update the respective section in the markdown.

### notes
- for editing, we could also create an excel file in onedrive that can be edited online.....using excel offers more possibilities, like protected the _path_ columns
- to start with, this can be a command line tool or a simple web-ui.
- the tool can use the credentials of the user performing the bulk-edit, this way, the _helix integration_ user doesn't need write access to the documents

**Comment by tripodsan** [comment]
Current Version:

- https://adobeioruntime.net/api/v1/web/tripod/default/helix-bulk-editor-0.0.2/#/

![image](https://user-images.githubusercontent.com/917628/74199179-48a63680-4c18-11ea-8e9b-6efc07c69d40.png)

![image](https://user-images.githubusercontent.com/917628/74199194-5956ac80-4c18-11ea-9394-397ba03829b8.png)

![image](https://user-images.githubusercontent.com/917628/74199238-7b502f00-4c18-11ea-87c0-a828ce4fedaa.png)

![image](https://user-images.githubusercontent.com/917628/74199262-860ac400-4c18-11ea-9c14-75862a32607d.png)

![image](https://user-images.githubusercontent.com/917628/74199360-c9653280-4c18-11ea-8721-58a786b52fb9.png)

![image](https://user-images.githubusercontent.com/917628/74199374-d41fc780-4c18-11ea-84ed-cc3e04d9a6d3.png)

![image](https://user-images.githubusercontent.com/917628/74199388-da15a880-4c18-11ea-80d0-8c01b6ca7d9d.png)

![image](https://user-images.githubusercontent.com/917628/74199438-06c9c000-4c19-11ea-91eb-f10d9df6cee1.png)

![image](https://user-images.githubusercontent.com/917628/74199522-455f7a80-4c19-11ea-84fe-85baefe04238.png)

![image](https://user-images.githubusercontent.com/917628/74199550-56a88700-4c19-11ea-8401-e2e27b133e16.png)

![image](https://user-images.githubusercontent.com/917628/74199594-73dd5580-4c19-11ea-9363-d11de2faab62.png)

![image](https://user-images.githubusercontent.com/917628/74199618-8061ae00-4c19-11ea-9991-8234abd994a2.png)

![image](https://user-images.githubusercontent.com/917628/74199628-89527f80-4c19-11ea-9e94-5f30a51b8cba.png)

**Comment by tripodsan** [comment]
@kamendola, @andreaskuefer would you be interrested in improve the design here?

**Comment by rofe** [comment]
Design improved
